const mongoose = require('mongoose');

const MONGO_URI = 'mongodb+srv://sso:sso123@sso.ixvhkmk.mongodb.net/hrms?retryWrites=true&w=majority&appName=SSO';

async function run() {
  await mongoose.connect(MONGO_URI);
  const dbName = 'GT_PMS_nitesh_legacy_442c114befbe';
  const db = mongoose.connection.useDb(dbName).db;
  
  const user = await db.collection('users').findOne({ email: 'baldaniyanitesh2003@gmail.com' });
  const w = await db.collection('workspaces').findOne();
  const p = await db.collection('projects').findOne();
  
  if (!user || !w || !p) {
    console.log('Missing basic data');
    process.exit(1);
  }

  const res = await db.collection('tasks').insertOne({
    title: 'Test Daily Task Generated by AI',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date(),
    workspaceId: w._id,
    projectId: p._id,
    tenantId: user.tenantId,
    assignees: [user._id],
    createdBy: user._id,
    createdAt: new Date(),
    updatedAt: new Date()
  });
  
  console.log('Inserted task:', res.insertedId);

  process.exit(0);
}

run().catch(console.error);
