const mongoose = require('mongoose');

/**
 * Enterprise EmployeeRoster Schema (Phase 2 Module 3)
 *
 * The final output calendar of all scheduling rules.
 * This represents the exact shift an employee is scheduled to work on a specific day.
 * 
 * Generated by the Roster Engine by analyzing:
 * 1. Shift Assignments (Company > Branch > Dept > Employee)
 * 2. Rotation Patterns
 * 3. Leave Validations
 * 4. Conflict Engines
 *
 * Multi-tenant: all documents scoped by `tenant` field.
 */

const employeeRosterSchema = new mongoose.Schema(
    {
        tenant: {
            type: String,
            required: true,
            index: true,
        },
        employeeId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Employee',
            required: true
        },
        date: {
            type: Date,
            required: true
        },
        shiftMasterId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'ShiftMaster',
            required: true
        },
        
        // ── ROSTER METADATA ───────────────────────────────────────────────
        isWeeklyOff: {
            type: Boolean,
            default: false
        },
        isHoliday: {
            type: Boolean,
            default: false
        },
        
        // ── SOURCE OF TRUTH (How did this shift get here?) ───────────────
        generatedBy: {
            type: String,
            enum: ['Assignment_Engine', 'Roster_Rotation', 'Manual_Override', 'Swap_Engine'],
            required: true
        },
        
        // ── OVERRIDE/SWAP TRACEABILITY ────────────────────────────────────
        swapRequestId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'ShiftSwapRequest',
            default: null
        },
        overriddenBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            default: null
        },

        // ── STATUS ────────────────────────────────────────────────────────
        status: {
            type: String,
            enum: ['Draft', 'Published'],
            default: 'Draft' // Drafts can be simulated. Published are final for attendance.
        }
    },
    { timestamps: true }
);

// ── INDEXES ──────────────────────────────────────────────────────────────
// One roster entry per employee per date
employeeRosterSchema.index({ tenant: 1, employeeId: 1, date: 1 }, { unique: true });
// For rendering the Roster Heatmap/Calendar for a month
employeeRosterSchema.index({ tenant: 1, date: 1, status: 1 });

module.exports = employeeRosterSchema;
